// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl7-qH4Uq837wjAKzv_s4ySO0YMGcshTU',
    appId: '1:536794645288:web:216ec251533aecfe15861d',
    messagingSenderId: '536794645288',
    projectId: 'bug-hunters-719f3',
    authDomain: 'bug-hunters-719f3.firebaseapp.com',
    storageBucket: 'bug-hunters-719f3.firebasestorage.app',
    measurementId: 'G-X8GPN06D5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj72tIk-Zf3Hi9uL4dRqdpWP-Vr_CjwEg',
    appId: '1:536794645288:android:edd1b95e6295174015861d',
    messagingSenderId: '536794645288',
    projectId: 'bug-hunters-719f3',
    storageBucket: 'bug-hunters-719f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9EjDQF3OvOjNNiSShfRjRiy_whJqSv9o',
    appId: '1:536794645288:ios:04dc2262ab38da3615861d',
    messagingSenderId: '536794645288',
    projectId: 'bug-hunters-719f3',
    storageBucket: 'bug-hunters-719f3.firebasestorage.app',
    iosBundleId: 'com.example.getFitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9EjDQF3OvOjNNiSShfRjRiy_whJqSv9o',
    appId: '1:536794645288:ios:04dc2262ab38da3615861d',
    messagingSenderId: '536794645288',
    projectId: 'bug-hunters-719f3',
    storageBucket: 'bug-hunters-719f3.firebasestorage.app',
    iosBundleId: 'com.example.getFitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl7-qH4Uq837wjAKzv_s4ySO0YMGcshTU',
    appId: '1:536794645288:web:175df5869528303b15861d',
    messagingSenderId: '536794645288',
    projectId: 'bug-hunters-719f3',
    authDomain: 'bug-hunters-719f3.firebaseapp.com',
    storageBucket: 'bug-hunters-719f3.firebasestorage.app',
    measurementId: 'G-G3KY5F0X90',
  );
}
